# Generated by Django 5.1.2 on 2025-06-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
