# Generated by Django 5.1.2 on 2025-06-29 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mainuser_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
