# Generated by Django 5.1.2 on 2025-06-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mainuser_created_at_mainuser_updated_at'),
    ]

    operations = [
    ]
